from dostuff.lib.mcp.mcp_client import MCPClient

BASE_SUBAGENT_INSTRUCTIONS = """You are a focused subagent operating in an isolated sub-loop.

Core Directives:
1. Complete the specified task accurately and concisely.
2. Rely strictly on the tools provided to gather facts. Do NOT fabricate information.
3. You do NOT have access to the parent conversation history. Use only the task description provided.
4. When finished, provide a clear, structured final report.
"""

RESTRICTED_SUBAGENT_TOOLS = {
    "delegate_to_subagent",  
    "delete_file",          
}

DEFAULT_SUBAGENT_TOOLS = ["read_file", "list_files", "create_file", "run_code", "get_mcp_tool_details", "call_mcp_tool", "search_mcp_tools","get_current_datetime"]

async def delegate_to_subagent(
    task: str,
    role: str,
    requested_tools: list[str] | None = None,
)->str:
    """
       Executes a subagent task in an isolated context loop.

       Args:
           task: Self-contained instructions detailing what the subagent must accomplish.
           role: Role framing descriptor used to specialize the subagent's system prompt.
           requested_tools: List of tool names requested by the parent model. If omitted, defaults to standard safe tools. Restricted tools (like recursion or destructive actions) are automatically stripped out.
           run_agent_loop_fn: The extracted core agent execution function.

       Returns:
           The final text output string generated by the subagent upon completion.
       """
    return ""

async def _impl_delegate_to_subagent(
    task: str,
    role: str,
    mcp_client: MCPClient,
    session_id: str,
    turn_id: str,
    requested_tools: list[str] | None = None,
) -> str:
    from dostuff.agent.loop import loop
    # 1. Resolve requested tools against safety boundaries
    requested_set = set(requested_tools) if requested_tools else set(DEFAULT_SUBAGENT_TOOLS)
    allowed_tool_names = list(requested_set - RESTRICTED_SUBAGENT_TOOLS)

    # print(f"requested tools: {requested_tools}")
    # print(f"allowed tools: {allowed_tool_names}")

    # 2. Frame the subagent system prompt
    subagent_system_instruction = f"""{BASE_SUBAGENT_INSTRUCTIONS}

\nYour Specific Role: {role}
"""

    working_history = [
           {
               "type": "user_input",
               "content": [{"type": "text", "text": task}],
           }
       ]
    # print(f"role: {role}")
    # print(f"user prompt: {task}")

    # 4. Run the subagent in an isolated context loop (fresh steps_history, smaller iteration cap)
    subagent_result = await loop(session_id, turn_id, task, subagent_system_instruction, mcp_client, working_history, 'subagent_loop', allowed_tool_names)

    # print(f"subagent result: {subagent_result}")
    
    return subagent_result